import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Navigation from "../component/navigation";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <Navigation />

        <h1> Welcome to NeXt Static & Auth0 demo!</h1>

        <p>The profile page will prompt the user to login once the user clicks on the link</p>
        <p>The my account page will only be visible if the user is logged in</p>

      </main>
    </>
  )
}
